Id: 3018
Title: App Engine as generic web host
Tags: appengine
Date: 2009-02-18T12:53:27-08:00
Format: Markdown
--------------
I believe that Google’s App Engine has a potential to be the next PHP.
By which I mean: low cost hosting option for not too sophisticated
websites.

I’m putting my money (or lack of it) where my mouth is and this website
is now hosted on App Engine. It’s a combination of static pages a blog
and a wiki. The code is written from scratch by myself but heavily based
on [Bloog](http://github.com/DocSavage/bloog/tree/master).

Writing things like that from scratch is a foolish thing to do. However,
I have some special needs (e.g. ability to use it more like a wiki) that
generic blogging engine like Bloog didn’t cover, and there’s always the
joy of learning a new thing (this is n-th technological transition for
this website, it used to run on Radio then Movable Type then WordPress
than static files generated by python script and served by nginx).

The code is less than 1000 lines of python and you can see it at
[github](http://github.com/kjk/web-blog/tree/master).

Getting back to App Engine as PHP: in App Engine I see many qualities
that made PHP popular:

-   it’s even easier to start developing in it - just install
    cross-platform SDK, write few lines of code and you have sth.
    runnig. No need to mess with Apache, PHP and a database setup.
-   language (Python) is easy to learn
-   deployment is trivial

It also has many advantages over basic PHP setup:

-   it comes with a database support built-in
-   it’s automagically scalable
-   hosting is free until you go over a very generous quota but even
    after that usage-based pricing should make it cheaper than even
    cheapest hosting (I overpay a little for my needs but before this
    site was hosted on \$20 slicehost account)
-   hopefully Google will keep it running well

Sure, there are many restrictions but basic (i.e. cheap) PHP setups also
have them.

To me it’s just a matter of time when clued in people start moving from
cheapo VPN hostings and LAMP stack to App Engine. It just makes lots of
sense.

What would accelerate this move is availability of installation-ready
software packages like blogs, wikis, forums etc., since not everyone is
up to coding everything from scratch. Those things are slowly popping
up, but it’s not a flood yet.
